---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mbank-prod
  labels:
    appcode: mbank
    env: production
    owner: mbank-admins
spec: {}
status: {}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-sa
