---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mdank-qa
  labels:
    appcode: mdank
    env: test
    owner: mdank-admins
spec: {}
status: {}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-sa
  namespace: mdank-qa


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: mdank-qa
spec:
  hard:
    cpu: "8"
    memory: 8G
    persistentvolumeclaims: "10"
    pods: "2"
    replicationcontrollers: "2"
    resourcequotas: "1"
    secrets: "5"
    services: "3"
